[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "common-serial-resolution"
version = "0.4.0"
description = "Framework agnostic library to resolve an Instance Id from a Serial Number"
readme = "README.md"
authors = [
  {name = "Eric Stasney", email = "estasney@cisco.com"}
]
requires-python = ">=3.12"


dependencies = [
    "snowflake-sqlalchemy",
    "sqlalchemy>2",
    "pydantic>2",
    "pydantic-settings",
    "boto3>=1.37.12",
    "pandas>=2.2.3",
    "openpyxl>=3.1.5",
    "xlsxwriter>=3.2.3",
]

[dependency-groups]
linters = [ "ruff>=0.9.0"]
dev = [
 "boto3-stubs-lite[essential]>=1.37.12",
 "keyring>=25.6.0",
 "pre-commit>=4.1.0",
 "pytest>=8.3.3",
 "wheel>=0.45.1",
]
[project.urls]
Repository = "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/common-serial-resolution"


[tool.uv]
default-groups = [ "linters", "dev"]


[tool.uv.sources.common-prefect-next]
git = "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/common_prefect_next.git"
branch = "master"

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = [ "A", "ANN", "ASYNC", "B", "C4", "EM", "ERA", "ERA", "F", "FA", "FIX", "G", "I", "ICN", "LOG", "NPY", "PD", "PERF", "PGH", "PIE", "PL", "RUF", "SIM", "SLOT", "T10", "TC", "TCH", "TD", "TRY",]
ignore = [ "F401", "F403", "PLR0913", "FA100", "FA102", "PLR", "PLC0415", "RUF012", "PD901", "ANN401", "ANN204",]


[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["I"]
"tests/**/*.py" = ["I", "ANN"]

[tool.ruff.lint.flake8-type-checking]
# Add quotes around type annotations, if doing so would allow
# an import to be moved into a type-checking block.
quote-annotations = true
runtime-evaluated-base-classes = ["pydantic.BaseModel", "common_serial_resolution.models.Model"]
exempt-modules = ["typing", "pydantic", "datetime"]
strict = false

[tool.pytest.ini_options]
addopts = "--strict-markers --capture=tee-sys"
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(name)s - %(message)s"
filterwarnings = ["ignore::DeprecationWarning" ]
