import json
import tempfile
from collections import defaultdict
from typing import Optional

import boto3
import pandas as pd
from sqlalchemy import create_engine, text, bindparam, String
from sqlalchemy.exc import ProgrammingError

from common import sec
from common.config import RunSettings
from common.models import S3FileUri, LocalFileUri, TagInstanceParams, DdlAction, TagInstanceResult


def tag_import(dc_engagement_id: Optional[int], run_settings: RunSettings) -> list[TagInstanceResult]:
    """
    Load data from uploaded spreadsheet. This was generated by export_tags
    - Check that each instance id is only tagged once
    - Once done, call stored procedure
    """

    # Load the workbook
    fp_uri = run_settings.request_metadata.file_input_location
    if fp_uri is None:
        raise ValueError("No file_input_location set in request_metadata")

    def get_from_s3(f: S3FileUri) -> str:
        s3 = boto3.client("s3")
        tf = tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False)
        s3.download_file(Bucket=f.bucket_name, Key=f.key, Filename=tf.name)
        return tf.name

    def get_from_local(f: LocalFileUri) -> str:
        return f.uri

    if fp_uri.file_type == "s3":
        fp = get_from_s3(fp_uri)
    elif fp_uri.file_type == "local":
        fp = get_from_local(fp_uri)
    else:
        raise ValueError(f"Unknown file type {fp_uri.file_type}")

    reader = pd.ExcelFile(fp)
    if dc_engagement_id is None:
        ws_eng_id = reader.parse(
            sheet_name=run_settings.ss.ws_engagement_id.sheet_name, dtype=run_settings.ss.ws_engagement_id.column_dtypes
        )
        # This is a single row
        dc_engagement_id = ws_eng_id.at[0, "dc_engagement_id"]
        if pd.isna(dc_engagement_id):
            raise ValueError("dc_engagement_id is null")

    df_mappings = reader.parse(
        sheet_name=run_settings.ss.ws_tagset_mappings.sheet_name, dtype=run_settings.ss.ws_tagset_mappings.column_dtypes
    )

    # Drop duplicate instance_id, tag_id pairs
    df_mappings = df_mappings.dropna().drop_duplicates(subset=["instance_id", "tag_id"])

    # Flag any instance_id that has more than one tag
    df_mappings["is_duplicated"] = df_mappings.groupby("instance_id")["instance_id"].transform("count") > 1

    if df_mappings["is_duplicated"].any():
        # TODO : Generate Excel file with error sheet
        raise ValueError("Duplicate instance_id, tag_id pairs found")

    # TODO : Call stored procedure to update tags

    # We will call the stored procedure once per tagset, group by tagset_id
    # We respect order of operations, so we will call the stored procedure in the order of the tagset_id
    tag_mappings = defaultdict(list)

    for row_tuple in df_mappings.itertuples():
        tag_mappings[row_tuple.tagset_id].append(row_tuple.instance_id)

    tag_mappings = dict(tag_mappings)

    tag_params = [
        TagInstanceParams(
            user_email=run_settings.request_metadata.requestor,
            tag_id=k,
            engagement_id=dc_engagement_id,
            ddl_action=DdlAction.set,
            instances=v,
        )
        for k, v in tag_mappings.items()
    ]

    engine = create_engine(
        sec.get_sf_pw(
            sec.check_env(run_settings.db_env),
            run_settings.get_warehouse(),  # Warehouse
            run_settings.schema_api,  # Schema
        ),
        connect_args={"log_max_query_length": 10_000},
    )

    proc_stmt = text(
        """
        CALL IDENTIFIER(:proc_name)(:params)
        """
    ).bindparams(bindparam("proc_name", run_settings.sp_tag_instances), bindparam("params", type_=String))

    results = []

    with engine.connect() as conn:
        for tag_param in tag_params:
            try:
                result_raw = conn.execute(proc_stmt, params=tag_param.json(by_alias=True)).scalar()
                result = json.loads(result_raw)
                if "success" in result and result["success"]:
                    print(f"Successfully called stored procedure for tag_id {tag_param.tag_id}")
                    results.append(TagInstanceResult(**{**tag_param.dict(), **dict(success=True)}))
                else:
                    print(f"Failed to call stored procedure for tag_id {tag_param.tag_id}")
                    print(result)
                    results.append(TagInstanceResult(**{**tag_param.dict(), **dict(success=False)}))
            except ProgrammingError as e:
                print(e)
                print(f"Failed to call stored procedure for tag_id {tag_param.tag_id}")
                results.append(TagInstanceResult(**{**tag_param.dict(), **dict(success=False)}))
            except ValueError as e:
                # Probably a JSONDecodeError
                print(e)
                print(result_raw)
                results.append(TagInstanceResult(**{**tag_param.dict(), **dict(success=False)}))

    return results
