[project]
name = "evidence-flows"
version = "0.2.0"
description = "Handle Uploads of Collector and Customer Files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
     "common-prefect-next>=0.15.1",
     "snowflake-sqlalchemy>=1.7.1",
     "sqlalchemy>=2.0.36",
     "pandas>=2.2.2",
     "boto3>=1.35.69",
     "xlsxwriter>=3.1.0",
     "prefect>3",
     "pydantic>=2,<3",
     "jinja2>=3.1.6",
     "toolz>=1.0.0",
     "common-serial-resolution>=0.4.0",
]

[build-system]
requires = [ "hatchling"]
build-backend = "hatchling.build"


[dependency-groups]
linters = [ "ruff>=0.8.0",]
dev = [
    "keyring>=25.6.0",
    "openpyxl>=3.1.5",
    "pre-commit>=4.2.0",
    "pytest>=8.3.3",
    "ruff>=0.12.2",
    "sqlglot>=26.33.0",
]

[tool.uv]
default-groups = [ "linters", "dev",]

[tool.uv.sources]
common-prefect-next = { git = "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/common_prefect_next.git", branch = "master" }
common-serial-resolution = { git = "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/common-serial-resolution.git", branch = "master" }

[tool.ruff]
target-version = "py312"
exclude = [".git", ".idea", ".vscode", "venv", ".venv", ".mypy_cache", ".pytest_cache", ".ruff", "site-packages", "tests", "scripts"]
preview = false

[tool.ruff.lint]
select = [ "A", "ANN", "ASYNC", "B", "C4", "EM", "ERA", "ERA", "F", "FA", "FIX", "G", "I", "ICN", "LOG", "NPY", "PD", "PERF", "PGH", "PIE", "PL", "RUF", "SIM", "SLOT", "T10", "TC", "TCH", "TD", "TRY",]
ignore = [ "F401", "F403", "PLR0913", "FA100", "FA102", "PLR", "PLC0415", "RUF012", "PD901", "ANN401","G004"]

[tool.pytest.ini_options]
log_cli = true
markers = [ "ddl",]

[tool.ruff.lint.per-file-ignores]
