[tool.poetry]
name = "serial-tagging"
version = "0.1.0"
description = ""
authors = ["ejurotic <ejurotic@cisco.com>"]
readme = "README.md"
packages = [{include = "serial_tagging"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
prefect = "0.15.3"
boto3 = "<=1.18.16"
pandas = "^1.1.3"
s3fs = "0.4"
hvac = "^0.11.0"
SQLAlchemy = "1.4.41"
awswrangler = "^2.10.0"
snowflake-sqlalchemy = "1.2.4"
orderedset = "^2.0.3"
XlsxWriter = "^3.0.1"
snowflake-connector-python = "2.7.12"
oyaml = "^1.0"
thoughtspot-tml = "^1.0.14"
thoughtspot-rest-api-v1 = "^1.0.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
