class TSException(Exception): ...


class TSCredsNotFoundError(TSException): ...


class TSTokenFetchError(TSException): ...


class TSMetadataFetchError(TSException): ...


class TSCreateConnectionError(TSException): ...


class TSCreateTableError(TSException): ...


class TSCreateWorksheetError(TSException): ...


class TSSearchMetadataError(TSException): ...


class TSExportMetadataError(TSException): ...


class TSImportMetadataError(TSException): ...


class TSShareMetadataError(TSException): ...


class TSUserMetadataSearchError(TSException): ...


class TSDeleteMetadataError(TSException): ...
