[project]
name = "dc-p1-htec-etl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9.*"
dependencies = [
    "boto3>=1.35.83",
    "numpy<2",
    "oracledb>=2.5.1",
    "pandas<2",
    "pyarrow<10",
    "snowflake-sqlalchemy>=1.7.2",
    "sqlalchemy==1.4.41",
]

[project.optional-dependencies]
linters = [
    "ruff>=0.8.3",
]

[dependency-groups]
dev = [
    "prefect==0.15.13",
]
