[project]
name = "common-prefect-template"
version = "0.6.1"
description = "Cookiecutter template for Prefect V3"
readme = "README.md"
authors = [
    { name = "Eric Stasney (estasney)", email = "estasney@cisco.com" }
]
requires-python = ">=3.12"
dependencies = [
    "cookiecutter>=2.6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"



[tool.ruff]
exclude = [".git", ".idea", ".vscode", "venv", ".venv", ".mypy_cache", ".pytest_cache", ".ruff", "site-packages", "tests", "scripts",
"*cookiecutter.project_slug"]
preview = false

[tool.ruff.lint]
select = ["I", "F", "ASYNC", "B", "C4", "T10", "FA", "ICN", "LOG", "SIM", "ERA", "PD", "PL", "NPY", "RUF", "TCH"]
ignore = ["F401", "F403", "PLR0913", "FA100", "FA102", "PLR", "PLC0415", "RUF012", "PD901"]

[tool.ruff.lint.per-file-ignores]

[tool.ruff.lint.flake8-type-checking]
# Add quotes around type annotations, if doing so would allow
# an import to be moved into a type-checking block.
quote-annotations = true
exempt-modules = ["typing", "typing_extensions", "datetime", "common_prefect_next.blocks.database", "common_prefect_next.blocks.environment"]

[tool.hatch.build.targets.wheel]
packages = ["{{cookiecutter.project_slug}}"]

[tool.uv.sources]
common-prefect-next = { git = "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/common_prefect_next.git" }

[dependency-groups]
dev = [
    "common-prefect-next",
    "prefect>=3.1.15",
    "pytest>=8.3.4",
]
