version: 0.2
env:
  variables:
    TENANT: cisco-dev
    FLOW_PATH: main.py
    PROJECT_NAME: "ElasticSearch Canvas Load"
  secrets-manager:
    API_KEY: prefect-api-key:prefect-api-key
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
    - python3 -m pip install --upgrade pip
    - pip install -r requirements_slim.txt
    - echo 'Building Wheels' && cat requirements_private.txt && pip wheel -r requirements_private.txt --no-deps --wheel-dir ./wheels
  build:
    commands:
      - echo "Logging into Prefect cloud"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 837578041534.dkr.ecr.us-east-1.amazonaws.com
      - prefect auth login -k "$API_KEY"
      - prefect auth switch-tenants --slug "$TENANT"
      - pip install ./wheels/*.whl
      - prefect register -p "$FLOW_PATH" --project "$PROJECT_NAME"
