[project]
name = "generate_evidence_flows"
version = "0.4.1"
description = "Generate evidence zones aggregates"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
     "common-prefect-next>=0.15.0",
     "prefect>=3.1.12",
     "snowflake-sqlalchemy>=1.7.1",
     "sqlalchemy>=2.0.36",
     "jinja2>=3.1.5",
]

[build-system]
requires = [ "hatchling"]
build-backend = "hatchling.build"


[dependency-groups]
linters = [ "ruff>=0.8.0",]
dev = [
    "pytest>=8.3.3",
]

[tool.uv]
default-groups = [ "linters", "dev",]

[tool.uv.sources]
common-prefect-next = { git = "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/common_prefect_next.git", branch = "master" }

[tool.ruff]
target-version = "py312"
exclude = [".git", ".idea", ".vscode", "venv", ".venv", ".mypy_cache", ".pytest_cache", ".ruff", "site-packages", "tests", "scripts"]
preview = false

[tool.ruff.lint]
select = [ "A", "ANN", "ASYNC", "B", "C4", "EM", "ERA", "ERA", "F", "FA", "FIX", "G", "I", "ICN", "LOG", "NPY", "PD", "PERF", "PGH", "PIE", "PL", "RUF", "SIM", "SLOT", "T10", "TC", "TCH", "TD", "TRY",]
ignore = [ "F401", "F403", "PLR0913", "FA100", "FA102", "PLR", "PLC0415", "RUF012", "PD901", "ANN401","G004"]

[tool.pytest.ini_options]
log_cli = true
markers = [ "ddl",]

[tool.ruff.lint.per-file-ignores]
