class ActionException(Exception): ...


class InvalidLiveboard(ActionException): ...


class InvalidAction(ActionException): ...


class CreateActionFailure(ActionException): ...


class CanvasDeletedException(ActionException): ...
