create or replace TABLE CPS_DB.CPS_DSCI_BR.BASE_NAMES (
	BASE_PRIMARY_ID NUMBER(38,0) NOT NULL,
	TABLE_NAME VARCHAR(500),
	primary key (BASE_PRIMARY_ID)
);
view_to_source_column_lineage
create or replace TABLE CPS_DB.CPS_DSCI_BR.VIEW_TO_SOURCE_COLUMN_LINEAGE (
	VIEW_NAME VARCHAR(255),
	VIEW_COLUMN VARCHAR(255),
	COLUMN_TYPE VARCHAR(50),
	SOURCE_TABLE VARCHAR(5000),
	SOURCE_COLUMN VARCHAR(5000),
	EXPRESSION_TYPE VARCHAR(100)
);