class CanvasException(Exception): ...


class CanvasNotFound(CanvasException): ...


class CanvasLiveboardNotFound(CanvasException): ...


class CanvasTableNotFoundError(CanvasException): ...


class CanvasTSTableAlreadyExists(CanvasException): ...


class CanvasTSWorksheetAlreadyExists(CanvasException): ...


class CanvasTMLCreationError(CanvasException): ...


class CanvasTableCreationError(CanvasException): ...


class CanvasWorksheetCreationError(CanvasException): ...


class CanvasLiveboardCreationError(CanvasException): ...


class CanvasTSDataSourceNotFoundError(CanvasException): ...


class CanvasS3LocationNotFound(CanvasException): ...


class CanvasTSLiveboardPushError(CanvasException): ...
