[project]
name = "common-prefect-next"
version = "0.16.11"
description = "Common Orchestration and Utilities for Prefect 3"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
 "prefect-aws>=0.5.1",
 "prefect>=3.0.11",
 "snowflake-sqlalchemy>=1.7.1",
 "sqlalchemy>=2.0.36",
 "pydantic>2",
 "jinja2>=3.1.5",
 "snowflake-connector-python>=3.11",
]

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
cli = "common_prefect_next.cli:cli"
tag = "common_prefect_next.cli:tag"

[project.optional-dependencies]
excel = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "xlsxwriter>=3.2.3",
]

[tool.ruff]
exclude = [ ".git", ".idea", ".vscode", "venv", ".venv", ".mypy_cache", ".pytest_cache", ".ruff", "site-packages", "tests", "scripts",]
preview = false
target-version = "py312"

[tool.ruff.lint]
select = ["A", "ANN", "ASYNC", "B", "C4", "EM", "ERA", "F", "FA","FIX", "ICN", "I", "LOG", "NPY", "PD", "PIE", "PL", "RUF", "SIM", "TC", "TD", "TRY", "T10" ]
ignore = [ "F401", "F403", "PLR0913", "FA100", "FA102", "PLR", "PLC0415", "RUF012", "PD901","ANN401", "ANN204"]

[tool.pytest.ini_options]
addopts = "--strict-markers --capture=tee-sys"
filterwarnings = ["ignore::DeprecationWarning"]
asyncio_mode = "auto"
mock_use_standalone_module = false
asyncio_default_fixture_loop_scope = "function"
log_cli=true
log_cli_level="INFO"
log_level="INFO"
log_format="%(asctime)s [%(levelname)s] %(message)s"
required_plugins = [ "pytest-asyncio", "pytest-mock"]

[dependency-groups]
dev = [
    "boto3-stubs-lite[essential]>=1.37.12",
    "hypothesis>=6.127.2",
    "keyring>=25.6.0",
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.3",
    "pytest-mock>=3.14.1",
    "ruff>=0.9.7",
]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["I001"]
"src/common_prefect_next/utils/snowflake_utils.py" = ["ANN"]

[tool.ruff.lint.flake8-type-checking]
quote-annotations = true
exempt-modules = [ "typing", "typing_extensions", "prefect_aws", "common_prefect_next.blocks",]
runtime-evaluated-base-classes = [ "prefect.blocks.core.Block", "prefect_aws.AwsCredentials", "prefect.blocks.notification.NotificationBlock",
"pydantic.BaseModel"]
