version: 0.2
env:
  variables:
    TENANT: cisco-dev
    FLOW_PATH: main.py
    PROJECT_NAME: "ElasticSearch Canvas Load"
  secrets-manager:
    API_KEY: prefect-api-key:prefect-api-key
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Logging into Prefect Cloud"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 837578041534.dkr.ecr.us-east-1.amazonaws.com
      - prefect auth login -k $API_KEY
      - prefect auth switch-tenants --slug $TENANT
      - prefect register -p $FLOW_PATH --project "$PROJECT_NAME"