version: 0.2
env:
  variables:
    TENANT: cisco-dev
    FLOW_PATH: parrallel_canvas_create.py
    PROJECT_NAME: "ElasticSearch Canvas Load"
    AWS_CLUSTER: "dev"
  secrets-manager:
    API_KEY: prefect-api-key:prefect-api-key
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
    - echo pwd
    - python3 -m pip install --upgrade pip
    - pip install -r requirements.txt
  build:
    commands:
      - echo "Logging into Prefect cloud"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 837578041534.dkr.ecr.us-east-1.amazonaws.com
      - docker version
      - prefect auth login -k $API_KEY
      - prefect auth switch-tenants --slug $TENANT
      - echo $PROJECT_NAME ${PROJECT_NAME}
      - prefect register -l $AWS_CLUSTER -p $FLOW_PATH --project "ElasticSearch Canvas Load"